/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLogo: typeof import('./src/components/AppLogo.vue')['default']
    BaseButton: typeof import('./src/components/ui/button/BaseButton.vue')['default']
    BaseCard: typeof import('./src/components/ui/card/BaseCard.vue')['default']
    BaseDatePicker: typeof import('./src/components/ui/datepicker/BaseDatePicker.vue')['default']
    BaseDialog: typeof import('./src/components/ui/dialog/BaseDialog.vue')['default']
    BaseInput: typeof import('./src/components/ui/input/BaseInput.vue')['default']
    BaseSelect: typeof import('./src/components/ui/select/BaseSelect.vue')['default']
    BaseTable: typeof import('./src/components/ui/table/BaseTable.vue')['default']
    BaseTextarea: typeof import('./src/components/textarea/BaseTextarea.vue')['default']
    BaseTextareaField: typeof import('./src/components/ui/textarea/BaseTextareaField.vue')['default']
    BaseToast: typeof import('./src/components/ui/toast/BaseToast.vue')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    InputText: typeof import('primevue/inputtext')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    Textarea: typeof import('primevue/textarea')['default']
    TextareaField: typeof import('./src/components/textarea/TextareaField.vue')['default']
    Toast: typeof import('primevue/toast')['default']
    ToggleButton: typeof import('primevue/togglebutton')['default']
    ToggleSwitch: typeof import('primevue/toggleswitch')['default']
  }
  export interface GlobalDirectives {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
